### PR TITLE
Add compatibility with Python 3.10

### LINKED ISSUE #6: Python 3.10 croaks with `AttributeError: module 'collections' has no attribute 'MutableMapping'`
Dear Jeremy,

thanks a stack for conceiving and maintaining the `json-store` package.

At https://github.com/daq-tools/kotori/pull/94, we just bumped the CI to use Python 3.10, but it croaked with `AttributeError: module 'collections' has no attribute 'MutableMapping'` [^1][^2].
```python
ImportError while loading conftest '/home/runner/work/kotori/kotori/test/conftest.py'.
test/conftest.py:12: in <module>
    from kotori import KotoriBootloader
kotori/__init__.py:27: in <module>
    from kotori.util.common import setup_logging
kotori/util/common.py:10: in <module>
    import json_store
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/json_store/__init__.py:3: in <module>
    from .json_store import *
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/json_store/json_store.py:25: in <module>
    class JSONStore(collections.MutableMapping):
E   AttributeError: module 'collections' has no attribute 'MutableMapping'
Error: Process completed with exit code 4.
```

Is there anything you could do about it?

With kind regards,
Andreas.

[^1]: https://github.com/daq-tools/kotori/runs/7312346751
[^2]: https://github.com/daq-tools/kotori/runs/7312346825

### PR DESCRIPTION
**Pull request by amotl**
Dear Jeremy,

this patch aims to resolve #6. I believe it is safe to drop support for Python 2 now, please let me know if you think differently.

**Edit: Adjusted patch to retain compatibility with Python 2.**

With kind regards,
Andreas.

### CODE REVIEW

**Comment by brainsik** [comment]
Hi, @amotl. Thanks for the PR. I'll take a real look at this in the next few days (currently traveling).

FWIW, I'd probably opt to keep things backwards compatible with Python 2 since I suspect it's a very small amount of extra code. For a full cutover to Python 3, I'd want to look at what could get cleaned up / modernized since the code is from another era.

Again, thanks for your help!

**Comment by amotl** [comment]
Hi Jeremy,

thanks a stack for your quick response. You are right. I've adjusted the patch to retain compatibility with Python 2.

With kind regards,
Andreas.

**Comment by brainsik** [comment]
Hey, @amotl. I've released 3.1 and uploaded it PyPI. This should unblock daq-tools/kotori#94 and hiveeyes/beradio#4.

**Comment by amotl** [comment]
Hi Jeremy,

thank you so much for turning this around so quickly!

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Jeremy,

for the sake of completeness, and once more being very grateful about your prompt reaction, I wanted to report back that Kotori just gained support for Python 3.10 as well, after resolving a few more other blockers down the line.

Enjoy your travels and with kind regards,
Andreas.

**Pull request merged**
